name: The Ramble Wanderings
favicon: null
layout_spectrum: 0.6658139517530799
typography_spectrum: 0.565817684167996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7583453061524779
  lightness: 0.8689757096581161
  saturation: 0.7878198882099241
  rhythmicContrast: 0.47643716749735177
purpose: []
