analytics: {}
color:
  brandColors:
    - '#90A8A0'
    - '#283868'
    - '#6088A8'
    - '#10A0F0'
    - '#78E0F8'
  brandStrength: 0.1875
  lightness: 0.868975
  rhythmicContrast: 0.476437
  saturation: 0.1875
cta: {}
layout_spectrum: 1
name: The Ramble Wanderings
opengraph: {}
purpose: []
typography_spectrum: 0.71659
