name: The Ramble Wanderings
favicon: null
layout_spectrum: 0.70209
typography_spectrum: 0.71659
title: As I wander through this fascination with life...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#90A8A0'
    - '#283868'
    - '#6088A8'
    - '#10A0F0'
    - '#78E0F8'
  brandStrength: 0.25
  lightness: 0.868975
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
